EmployeeMaster/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/',include("employee.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/urls.py
from django.urls import path
from employee import views


urlpatterns=[
    path("account/signup",views.UseregistrationView.as_view(),name="sign-up"),
    path("account/login",views.LogInView.as_view(),name="log-in"),
    path("user/reg",views.EmployeeCreateView.as_view(),name="emp-reg"),
    path("user/list",views.EmployeeListView.as_view(),name="emp-list"),
    path("base",views.BaseView.as_view(),name="emp-base"),
    path("user/detail/<str:emp_id>",views.EmployeeDetailView.as_view(),name="emp-view"),
    path("user/edit/<str:emp_id>",views.EmployeeEditView.as_view(),name="emp-edit"),
    path("user/remove/<str:emp_id>",views.removeview,name="emp-remove"),
    path("account/signout",views.signout,name="sign-out")

]

employee/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Employee(models.Model):
    employee_name=models.CharField(max_length=20)
    image=models.ImageField(upload_to="images",null=True)
    email=models.EmailField(unique=True)
    password=models.CharField(max_length=15)
    phone=models.PositiveIntegerField()
    address=models.CharField(max_length=200)

employee/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from employee.models import Employee


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model=User
        fields=[
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2"
        ]

class LogInForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)


class EmployeeRegistrationForm(ModelForm):
    class Meta:
        model = Employee
        fields="__all__"

        widgets={

            "employee_name": forms.TextInput(attrs={"class": "form-control"}),
            "image": forms.FileInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
            "phone": forms.NumberInput(attrs={"class": "form-control"}),
            "address": forms.TextInput(attrs={"class": "form-control"}),


        }

employee/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,CreateView,FormView,TemplateView,UpdateView
from employee.forms import UserRegistrationForm,LogInForm,EmployeeRegistrationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from employee.models import Employee
from django.utils.decorators import  method_decorator


def sign_required(fn):
    def wrapper(request,*args,**kwargs):
        if request.user.is_authenticated:
            return fn(request,*args,**kwargs)
        else:
            messages.error(request,"login first")
            return redirect("log-in")

    return wrapper




class UseregistrationView(CreateView):
    form_class = UserRegistrationForm
    template_name = "register.html"
    model = User
    success_url = reverse_lazy("log-in")



class LogInView(FormView):
    form_class = LogInForm
    template_name = "login.html"
    model = User
    def post(self, request, *args, **kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get("username")
            password=form.cleaned_data.get("password")
            user=authenticate(request,username=username,password=password)
            if user:
                print("success")
                login(request,user)
                return redirect("emp-list")
            else:
                messages.error(request,"login failed")
                return render(request,self.template_name,{"form":form})

@method_decorator(sign_required,name="dispatch")
class EmployeeCreateView(View):
    def get(self,request,*args,**kwargs):
        form=EmployeeRegistrationForm()
        return render(request,"employeeregisteration.html",{"form":form})
    def post(self,request,*args,**kwargs):
        form=EmployeeRegistrationForm(request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,"phone details successfully added")
            return redirect("emp-list")
        else:
            messages.error(request,"phone details adding failed")
            return render(request, "employeeregisteration.html")





@method_decorator(sign_required,name="dispatch")
class EmployeeListView(View):
    def get(self,request,*args,**kwargs):
        qs=Employee.objects.all()
        return render(request, "list.html", {"employee": qs})
@method_decorator(sign_required,name="dispatch")
class BaseView(TemplateView):
    template_name = "base.html"

@method_decorator(sign_required,name="dispatch")
class EmployeeDetailView(View):
    def get(self, request, *args, **kwargs):
        id=kwargs.get("emp_id")
        employee=Employee.objects.get(id=id)
        return render(request,"details.html",{"employee":employee})


@method_decorator(sign_required,name="dispatch")
class EmployeeEditView(UpdateView):
    model = Employee
    form_class = EmployeeRegistrationForm
    template_name = "update.html"
    success_url = reverse_lazy("emp-list")
    pk_url_kwarg = "emp_id"

@sign_required
def removeview(request,*args,**kwargs):
    id=kwargs.get("emp_id")
    phone = Employee.objects.get(id=id)
    phone.delete()
    messages.success(request,"successfully deleted")
    return redirect("emp-list")

@sign_required
def signout(request,*args,**kwargs):
    logout(request)
    return redirect("log-in")

employee/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Simple Sidebar - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    </head>
    <body>
        <div class="d-flex" id="wrapper" >
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper">
                <div class="sidebar-heading border-bottom bg-light"><strong class="text-dark">Employee Management</strong></div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 bg-light" href="{%url 'emp-reg'%}"><strong>ADD NEW EMPLOYEE</strong></a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 bg-light" href="#!">Shortcuts</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 bg-light" href="#!">Overview</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 bg-light" href="#!">Events</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 bg-light" href="#!">Profile</a>
                    <a class="list-group-item list-group-item-action list-group-item-light p-3 bg-light" href="#!">Status</a>
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0 ">
                                <li class="nav-item active"><a class="nav-link " href="{%url 'emp-list'%}">Home</a></li>
                                <li class="nav-item"><a class="nav-link " href="#!">Link</a></li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle " id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user}}</a>
                                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="#!">Action</a>
                                        <a class="dropdown-item" href="#!">Another action</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{%url 'sign-out'%}">log out</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid ">
                    {%block body_block%}
                    {%endblock%}
                </div>


        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
</body>
</html>

employee/templates/details.html
{%extends 'base.html'%}
{%block body_block%}
<div class="container">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <div class="card mb-3 mt-5 ms-5 text-bg-light" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{employee.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title ms-3">{{employee.employee_name}}</h5>
          <hr>
          <ul>
              <li><strong>EMAIL :</strong>{{employee.email}}</li>
              <li><strong>PASSWORD :</strong>{{employee.password}}</li>
              <li><strong>PHONE :</strong>{{employee.phone}}</li>
              <li><strong>ADDRESS :</strong>{{employee.address}}</li>
          </ul>

        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>

</div>
    </div>
    <div class="col-2"></div>
  </div>
</div>



{%endblock%}

employee/templates/employeeregisteration.html
{%extends 'base.html'%}
{%block body_block%}
{%load static%}

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4"><h1 class="text-center">Employee Details</h1></div>
        <div class="col-4">
            {%if messages%}
                {%for msg in messages%}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{msg}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>

            {%endfor%}
        {%endif%}
    </div>
</div>
<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                 <div class="row">
            <div class="col-4 mt-">
                <img src="{%static 'assets/pg.png'%}" class="card-img-top" alt="">
                <input type="file" name="image" id="id_image" class="mt-2">
            </div>
            <div class="col-4 mt-5">
                <input type="text" name="employee_name" id="id_employee_name" placeholder="Employee Name" class="form-control mt-3">
                <input type="email" name="email" id="id_email" placeholder="email" class="form-control mt-3">
                <input type="password" name="password" id="id_password"  placeholder="password" class="form-control mt-3">
                <div class="mt-3">
                    <button type="submit" class="btn btn-secondary">submit</button>
                    <a href="{%url 'emp-list'%}">lists</a>
                </div>
            </div>
            <div class="col-4 mt-5">
                <input type="number" name="phone" id="id_phone" placeholder="phone" class="form-control mt-3">
                <input type="text" name="address" id="id_address" placeholder="address" class="form-control mt-3">
            </div>
        </div>
            </div>
            <div class="col-2"></div>
        </div>


    </form>


</div>

<!--<form action="" method="post" enctype="multipart/form-data">-->
<!--    {%csrf_token%}-->
<!--    {{form.as_p}}-->
<!--    <button type="submit">create</button>-->
<!--</form>-->



{%endblock%}

employee/templates/list.html
{%extends 'base.html'%}
{%block body_block%}


<table class="table table-striped table-dark">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">NAME</th>
        <th scope="col">EMAIL</th>
        <th scope="col">PHONE</th>
        <th scope="col">ADDRESS</th>
        <th scope="col">ACTIONS</th>
    </tr>
    </thead>

    {%for emp in employee%}
    <tbody>

    <tr>

        <td>{{emp.id}}</td>
        <td>{{emp.employee_name}}</td>
        <td>{{emp.email}}</td>
        <td>{{emp.phone}}</td>
        <td>{{emp.address}}</td>
        <td>
            <a href="{%url 'emp-view' emp.id %}">view</a>
            <a href="{%url 'emp-edit' emp.id%}">edit</a>
            <a href="{%url 'emp-remove' emp.id%}">delete</a>
        </td>
    </tr>

    </tbody>
    {%endfor%}
</table>


{%endblock%}

employee/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/462b907c66.js" crossorigin="anonymous"></script>
</head>
<body>
<section class="vh-100"0>
    <div class="container py-5 h-100">
        <div class="row d-flex align-items-center justify-content-center h-100">
            <div class="col-md-8 col-lg-7 col-xl-6">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg"
                     class="img-fluid" alt="Phone image">
            </div>
            <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                {%for msg in messages%}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>oops!</strong> You must login.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {%endfor%}
                <form method="post">
                    {%csrf_token%}

                    <!-- Email input -->
                    <div class="form-outline mb-4">
                        <input type="text" id="id_username" name="username" class="form-control form-control-lg"
                               placeholder="Username"/>

                    </div>

                    <!-- Password input -->
                    <div class="form-outline mb-4">
                        <input type="password" id="id_password" name="password" class="form-control form-control-lg"
                               placeholder="Password"/>

                    </div>

                    <div class="d-flex justify-content-around align-items-center mb-4">
                        <!-- Checkbox -->
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="form1Example3" checked/>
                            <label class="form-check-label" for="form1Example3"> Remember me </label>
                        </div>
                        <a href="#!">Forgot password?</a>
                    </div>

                    <!-- Submit button -->
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>
                    </div>

                    <div class="  align-items-center my-4">
                        <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
                    </div>


                    <div class="d-grid gap-2 ">
                        <a class="btn btn-primary btn-lg btn-block" style="background-color: #3b5998" href="#!"
                           role="button">
                            <i class="fab fa-facebook-f me-2"></i>Continue with Facebook
                        </a>
                        <a class="btn btn-primary btn-lg btn-block" style="background-color: #55acee" href="#!"
                           role="button">
                            <i class="fab fa-twitter me-2"></i>Continue with Twitter</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</section>


</body>
</html>

employee/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</head>
<body>
<form action="" method="post">
  {%csrf_token%}
  <section class="vh-100" style="background-color: #eee;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-5" >Sign up</p>

                <form class="mx-1 mx-md-4">

                  <div class="d-flex flex-row align-items-center mb-1">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-1">
                      <input type="text" id="id_first_name" class="form-control form-control-lg" name="first_name" />
                      <label class="form-label" for="id_first_name">firstname</label>
                    </div>
                   <div class="d-flex flex-row align-items-center mb-1">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="text" id="id_second_name" class="form-control form-control-lg" name="second_name" />
                      <label class="form-label" for="id_second_name">second name</label>
                    </div>
                  </div>
                  </div>
                    <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="text" id="id_username" class="form-control form-control-lg" name="username" />
                      <label class="form-label" for="id_first_name">username</label>
                    </div>
                  </div>


                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="email" id="id_email" class="form-control" name="email" />
                      <label class="form-label" for="id_email">email</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="password" id="id_password1" class="form-control" name="password1" />
                      <label class="form-label" for="id_password1">Password</label>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <input type="password" id="id_password2" class="form-control" name="password2" />
                      <label class="form-label" for="id_password2">Repeat your password</label>
                    </div>
                  </div>

                  <div class="form-check d-flex justify-content-center mb-5">
                    <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3c" />
                    <label class="form-check-label" for="form2Example3">
                      I agree all statements in <a href="#!">Terms of service</a>
                    </label>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <button type="submit" class="btn btn-primary btn-lg">Register</button>
                  </div>

                </form>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                  class="img-fluid" alt="Sample image">

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</form>

</form>
</body>
</html>

employee/templates/update.html
{%extends 'base.html'%}
{%block body_block%}
{%load static%}

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4"><h1 class="text-center">Employee Details</h1></div>
        <div class="col-4">
            {%if messages%}
                {%for msg in messages%}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>{{msg}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>

            {%endfor%}
        {%endif%}
    </div>
</div>
<div class="container">
    <form action="" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">register</button>
<!--        <div class="row">-->
<!--            <div class="col-2"></div>-->
<!--            <div class="col-8">-->
<!--                 <div class="row">-->
<!--            <div class="col-4 mt-">-->
<!--                <img src="{%static 'assets/pg.png'%}" class="card-img-top" alt="">-->
<!--                <input type="file" name="image" id="id_image" class="mt-2">-->
<!--            </div>-->
<!--            <div class="col-4 mt-5">-->
<!--                <input type="text" name="employee_name" id="id_employee_name" placeholder="Employee Name" class="form-control mt-3">-->
<!--                <input type="email" name="email" id="id_email" placeholder="email" class="form-control mt-3">-->
<!--                <input type="password" name="password" id="id_password"  placeholder="password" class="form-control mt-3">-->
<!--                <div class="mt-3">-->
<!--                    <button type="submit" class="btn btn-secondary">submit</button>-->
<!--                    <a href="{%url 'emp-list'%}">lists</a>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="col-4 mt-5">-->
<!--                <input type="number" name="phone" id="id_phone" placeholder="phone" class="form-control mt-3">-->
<!--                <input type="text" name="address" id="id_address" placeholder="address" class="form-control mt-3">-->
<!--            </div>-->
<!--        </div>-->
<!--            </div>-->
<!--            <div class="col-2"></div>-->
<!--        </div>-->


    </form>


</div>



{%endblock%}